### PR TITLE
Refactor to remove deprecated character use

### PR DESCRIPTION
**Pull request by morganzellers**
Removed use of the deprecated `.characters` from codebase and test.

### CODE REVIEW

**Comment by morganzellers** [comment]
Will resolve later today

**Comment by iamjono** [comment]
I did a manual merge... can you check all is good with the merge as per your changes, and I can close.
I haven't tagged it as a new version yet...
Thanks!!!

**Comment by morganzellers** [comment]
@iamjono Yup all changes look to be present!

**Comment by wdcurry** [comment]
I just grabbed the repo to test, and see quite a few deprecated warnings.. just a FYI.. 

I just used pod "String+Extensions" (replacing the double quotes for the single of course)...

**Pull request closed without merging**
